baseURL: "https://vigilant-engelbart-767a09.netlify.app/"
languageCode: en-us
title: New_Hugo_site
theme: PaperMod

menu:
  main:
    - identifier: price
      name: Prices
      url: /prices/
      weight: 10